// WARNING: This is a GENERATED file - do not modify - Generated by Circom Make
// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.17;

import "../types/IVerifier.sol";
import "../types/IVerifierEVM3x2x1v4.sol";

contract VerifierEVM3x2x1v4 is IVerifier {
    IVerifierEVM3x2x1v4 public immutable verifier;
    uint16 constant inputAmount = 25;

    constructor(address verifierInstance) {
        verifier = IVerifierEVM3x2x1v4(verifierInstance);
    }

    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[] memory input,
        uint256
    ) external view returns (bool) {
        require(input.length == inputAmount, "Invalid input length");
        uint256[inputAmount] memory fixedInput;
        for (uint16 i = 0; i < input.length; i++) {
            fixedInput[i] = input[i];
        }
        return verifier.verifyProof(a, b, c, fixedInput);
    }
}

