// WARNING: This is a GENERATED file - do not modify - Generated by Circom Make
// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.17;

interface IVerifierEVM4x2x1v4 {
  function verifyProof(
    uint256[2] memory a,
    uint256[2][2] memory b,
    uint256[2] memory c,
    uint256[30] memory input
  ) external view returns (bool);
}
